//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedicalReminder.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedicalReminder.DAL.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C73AE453-3122-4270-B134-ECF937ED7F2C.
        /// </summary>
        internal static string DoctorId1 {
            get {
                return ResourceManager.GetString("DoctorId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 868ACD3E-6806-4DB9-826B-D875A34F2283.
        /// </summary>
        internal static string DrugId1 {
            get {
                return ResourceManager.GetString("DrugId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 44919B15-70AD-4C8E-B82E-8F80497A7B8A.
        /// </summary>
        internal static string DrugId2 {
            get {
                return ResourceManager.GetString("DrugId2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 92C9B88E-BEBE-4892-BC90-6D0BC5D90FB3.
        /// </summary>
        internal static string PrescriptionId1 {
            get {
                return ResourceManager.GetString("PrescriptionId1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 43AA5D6A-6FDC-489F-8907-EE48AAF06D68.
        /// </summary>
        internal static string UserId1 {
            get {
                return ResourceManager.GetString("UserId1", resourceCulture);
            }
        }
    }
}
